# Generated by Django 4.2.3 on 2023-08-01 11:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('height', models.FloatField(verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Координаты',
                'verbose_name_plural': 'Координаты',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(blank=True, max_length=255, verbose_name='Название фото 1')),
                ('image_1', models.CharField(blank=True, default=None, verbose_name='Фотография 1')),
                ('title_2', models.CharField(blank=True, max_length=255, verbose_name='Название фото 2')),
                ('image_2', models.CharField(blank=True, default=None, verbose_name='Фотография 2')),
                ('title_3', models.CharField(blank=True, max_length=255, verbose_name='Название фото 3')),
                ('image_3', models.CharField(blank=True, default=None, verbose_name='Фотография 3')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, max_length=10, verbose_name='Зима')),
                ('summer', models.CharField(blank=True, max_length=10, verbose_name='Лето')),
                ('autumn', models.CharField(blank=True, max_length=10, verbose_name='Осень')),
                ('spring', models.CharField(blank=True, max_length=10, verbose_name='Весна')),
            ],
            options={
                'verbose_name': 'Уровень сложности',
                'verbose_name_plural': 'Уровни сложности',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='Электронная почта')),
                ('fam', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('otc', models.CharField(max_length=150, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,12}$')], verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(max_length=255, verbose_name='Название препятствия')),
                ('title', models.CharField(max_length=255, verbose_name='Название вершины')),
                ('other_titles', models.CharField(max_length=255, verbose_name='Другое название')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'новый'), ('pending', 'модератор взял в работу'), ('accepted', 'модерация прошла успешно'), ('rejected', 'модерация прошла, информация не принята')], default='new', max_length=10, verbose_name='Статус')),
                ('connect', models.TextField(blank=True, verbose_name='Соединяет')),
                ('coords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval_app.coords')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval_app.images')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval_app.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='pereval_app.users')),
            ],
            options={
                'verbose_name': 'Перевал',
                'verbose_name_plural': 'Перевалы',
            },
        ),
    ]
