# Generated by Django 4.2.3 on 2023-07-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Уровень сложности', 'verbose_name_plural': 'Уровни сложности'},
        ),
        migrations.AlterModelOptions(
            name='perevaladded',
            options={'verbose_name': 'Перевал', 'verbose_name_plural': 'Перевалы'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
