# Generated by Django 4.2.3 on 2023-07-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval_app', '0002_alter_level_options_alter_perevaladded_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
