# Generated by Django 4.2.3 on 2023-07-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval_app', '0002_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=30, unique=True, verbose_name='Электронная почта'),
        ),
    ]
